[build]
    command = "yarn build"
    publish = "dist"
    
[dev]
    framework = "#custom"
    command = "yarn start"
    autoLaunch = false
    targetPort = 3000

[functions]
    directory = "api"
    external_node_modules = ["express"]