[build]
    command = "yarn build"
    publish = "dist"
    
[dev]
    framework = "#custom"
    command = "yarn start"
    autoLaunch = false
    targetPort = 3000

[[headers]]
    for = "/*"
    [headers.values]
        X-Robots-Tag = "noindex, nofollow"

[[redirects]]
    from = "https://dm3kalselteng2021.netlify.app/*"
    to = "https://dm3kalselteng.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/daftar"
    to = "https://forms.gle/VG2JYYgqgWFAe2kKA"
    status = 301
    force = true

[[redirects]]
    from = "/unduh"
    to = "https://bit.ly/DM3KalseltengFiles"
    status = 301
    force = true

[[redirects]]
    from = "/timseleksi/tugas1"
    to = "https://forms.gle/gGp6isAg1DCAphXG6"
    status = 302
    force = true

[[redirects]]
    from = "/timseleksi/tugas2"
    to = "/soon"
    status = 302
    force = true

[[redirects]]
    from = "/tugas1"
    to = "https://forms.gle/9SUJjgzWU1J3T6XE6"
    status = 301
    force = true

[[redirects]]
    from = "/tugas2"
    to = "/soon"
    status = 302
    force = true

[[redirects]]
    from = "/wawancara"
    to = "/soon"
    status = 302
    force = true

[[redirects]]
    from = "/sosialisasi-zoom"
    to = "https://us02web.zoom.us/j/85478911418?pwd=SFM1bUNYZ1JFRDd1VkxlcDJZOGMyUT09s"
    status = 301
    force = true