[build]
    command = "yarn build"
    publish = "dist"
    
[dev]
    framework = "#custom"
    command = "yarn start"
    autoLaunch = false
    targetPort = 3000

[[redirects]]
    from = "https://dm3kalselteng2021.netlify.app/*"
    to = "https://dm3kalselteng.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/daftar"
    to = "https://forms.gle/VG2JYYgqgWFAe2kKA"
    status = 301
    force = true

[[redirects]]
    from = "/unduh"
    to = "https://bit.ly/DM3KalseltengFiles"
    status = 301
    force = true

[[redirects]]
    from = "/timseleksi"
    to = "/soon"
    status = 302
    force = true

[[redirects]]
    from = "/tugas1"
    to = "/soon"
    status = 302
    force = true

[[redirects]]
    from = "/tugas2"
    to = "/soon"
    status = 302
    force = true

[[redirects]]
    from = "/wawancara"
    to = "/soon"
    status = 302
    force = true